### ISSUE TITLE
Phraseapp syncs for backend branches introduces unexpected changes

### ISSUE THREAD

**Issue by Edgar-Friendly** [iknow/phraseapp_updater#14] opened 2022-09-26 04:17 UTC
We've noticed that when creating a backend branch and adding in changes on phraseapp, the diff shows unexpected changes after syncing it via the phraseapp updater ([here](https://jenkins.aws.iknow.jp/job/replace/job/phraseapp/job/update_phraseapp_branch/build?delay=0sec)). Chris and I have found this bug multiple times, after making minor translation edits for backend strings, which requires stripping the unintended changes manually in every case. This behavior is not normally found in frontend branch syncs.

We've discussed the details for both cases [here](https://biboglobal.slack.com/archives/G420W15LN/p1655286113214569?thread_ts=1655281551.416169&cid=G420W15LN) and it looks like it is something easily reproduced.

These are some example PRs:
https://github.com/iknow/eikaiwa_content/pull/2021
https://github.com/iknow/eikaiwa_content/pull/1922
https://github.com/iknow/eikaiwa_content/pull/2049

**Comment by chrisandreae** [comment] 2023-05-17 06:16
I expect this to have been fixed by https://github.com/iknow/phraseapp_updater/pull/17. The problem was that sometimes uploading a given language's strings to the new phraseapp project would silently fail, and so syncing back would delete them. #17 updates the client to check and retry.

Please let me know if the issue or a similar one is seen again.

**Closed as completed by chrisandreae** 2023-05-17 06:16 UTC

**Comment by Edgar-Friendly** [comment] 2023-06-16 06:16
@chrisandreae It seems this is happening again for BE branches.
I created [#2333](https://github.com/iknow/eikaiwa_content/pull/2333) as part of a plan to update localizations for some strings and re-ran the updater [on jenkins](https://jenkins.aws.iknow.jp/job/replace/job/phraseapp/job/update_phraseapp_branch/build?delay=0sec) without having made any actual changes in the TMS (Phrase) yet. The [differential](https://github.com/iknow/eikaiwa_content/pull/2333/files) shows a number of changes that were never made, alas.

**Comment by Edgar-Friendly** [comment] 2023-06-16 06:24
I did this for a FE branch too ([#6672](https://github.com/iknow/eikaiwa_content_frontend/pull/6672)) with no added changes in the [differential](https://github.com/iknow/eikaiwa_content_frontend/pull/6672/files) as expected. Seems to be affecting the backend only.

**Comment by chrisandreae** [comment] 2023-06-16 09:12
This looks a little different from the previous issue we saw on the frontend, which was entire languages getting lost because the Phrase upload process silently failed. I wonder what's causing this one 😢.

**Comment by chrisandreae** [comment] 2023-06-16 09:13
~One thing worth checking before digging in more is that when Jenkins runs phraseapp_updater for the backend it's using the latest version of it.~ Checked: it is.

**Comment by Edgar-Friendly** [comment] 2023-06-19 06:11
Gosh, yeah. 😖 There's no rush to get it addressed for the BE, but it'd would certainly save time from having to strip the unintended changes from these syncs. It was only until earlier this year that was a random issue for FE branch syncs.

@raushan You mentioned on Friday there was something strange that happened when you tried to sync in locale changes for the spotlight strings. 🤔 We didn't get a chance to dig into it and I'm not sure it's related, but could you please share some more details on that just in case?

**Comment by chrisandreae** [comment] 2023-06-19 08:45
So I'm looking into it a bit; I'm pretty worried it's something that Phrase is doing. I [pulled out](https://github.com/iknow/phraseapp_updater/pull/19) the normalization code into a separate command, and I don't see the `distance_in_words` strings getting deleted.

I'm going to merge the [renormalization](https://github.com/iknow/eikaiwa_content/pull/2341) to reduce the size of the diff we see in the future when debugging this.

**Comment by chrisandreae** [comment] 2023-06-19 09:33
Moreover, I've confirmed that this YAML fragment is definitely in the English file getting uploaded to Phrase:
```yaml
  datetime:
    distance_in_words:
      x_hours:
        one: 1 hour
        other: "%{count} hours"
```
but it doesn't appear in the resulting Phrase project UI

**Comment by chrisandreae** [comment] 2023-06-19 09:38
Here's the resulting project from uploading it: https://app.phrase.com/accounts/engoo-replace/projects/test-backend-sync-2/dashboard

Maybe you could ask Phrase about it?

**Comment by raushan** [comment] 2023-06-20 03:33
> @raushan You mentioned on Friday there was something strange that happened when you tried to sync in locale changes for the spotlight strings. 🤔 We didn't get a chance to dig into it and I'm not sure it's related, but could you please share some more details on that just in case?

Basically I had a [diff](https://github.com/iknow/eikaiwa_content_frontend/pull/6663/commits/716ad8d3d339f149866437abac819d419ca64b06) that looks something like
```
diff --git a/config/locales/en.json b/config/locales/en.json
index 3f61b667b..f13223969 100644
--- a/config/locales/en.json
+++ b/config/locales/en.json
@@ -8550,6 +8550,10 @@
     },
     "people": {
       "actions": {
+        "action-menu": {
+          "caller": "Caller actions",
+          "peer": "Call actions for %{user}"
+        },
         "meeting-lock": {
           "button": "End Meeting",
           "confirm-modal": {
@@ -8568,22 +8572,24 @@
             "title": "Start Meeting Early"
           }
         },
-        "mute": {
-          "title": {
-            "caller": "Turn off Microphone",
-            "peer": "Mute %{name}'s Microphone"
-          }
-        },
+        "mute": "Mute",
         "mute-all": "Mute Everyone Else",
         "pinning": {
           "pin": "Pin",
           "unpin": "Unpin"
         },
-        "unmute": {
-          "title": {
-            "caller": "Turn on Microphone"
-          }
-        }
+        "spotlighting": {
+          "caller-spotlighted": "You have been spotlighted by %{name}",
+          "remove-spotlight": "Remove spotlight",
+          "spotlight": "Spotlight for everyone"
+        },
+        "unmute": "Unmute"
+      },
```

And after running a phraseapp sync it didn't seem to pull in the new `people.actions.mute` and `people.actions.unmute` strings and instead left the `people.actions.mute.title.*` and the `people.actions.unmute.title.*` strings that were supposed to be removed. 
There's always a chance I did something strange when creating my dedicated locales branch though so as of now I'm not certain that the script is at fault. The data for the new strings seems to be in phraseapp though, so I can fix it locally.
